# Tasks for openvpn role                                                            
# file: roles/openvpn/tasks/main.yml                                                
---                                                                                 
- name: install packages                                                            
  apt: pkg={{ item }} state=present install_recommends=no                           
  with_items:                                                                       
    - openvpn
- name: ensure openvpn folder exists                                                
  file: dest=/etc/openvpn                                                           
        state=directory                                                             
        owner=root mode=0775                                     
#^^^must be world readable                                                          
                                                                                    
- name: ensure ccd folder exists                                                    
  file: dest=/etc/openvpn/ccd                                                       
        state=directory                                                             
        owner=root group=root mode=0755                                             
                                                                                    
- name: openvpn common config items                                                 
  copy: src=common/{{ item }}                                                       
        dest=/etc/openvpn/                                                          
        owner=root group=root mode=0644                                             
  with_items:                                                                       
    - ca.crt                                                                        
    - server.crt                                                                    
    - server.key.enc                                                                
    - dh2048.pem                                                                    
    #- crl.pem <--copy up by hand initially.
  notify:                                                                           
    - restart openvpn                                                               
                                                                                    
- name: decrypt keys                                                                
  shell: openssl enc -aes-256-ctr -d -in /etc/openvpn/{{ item }}.key.enc -out /etc/openvpn/{{ item }}.key -k {{ decryptkey }}
  with_items:                                                                       
    - server                                                                        
                                                                                    
- name: fix key permissions                                                         
  file: dest=/etc/openvpn/{{ item }}.key mode=0600 owner=root group=root            
  with_items:                                                                       
    - server                                                                        
                                                                                    
- name: openvpn host config items                                                   
  copy: src={{ inventory_hostname }}/{{ item }}                                     
        dest=/etc/openvpn/                                                          
        owner=root group=root mode=0644                                             
  with_items:                                                                       
    - openvpn.conf
  notify:                                                                           
    - restart openvpn                                                            

- name: sysctl   
  template: src=sysctl.conf.j2                                                   
        dest=/etc/sysctl.conf                                                    
        owner=root group=root mode=0644                                          
  notify:                                                                        
    - reload sysctl                  
